apiVersion: v1
data:
  adminPassword: ${foundryvtt.admin_password}
  licenseKey: ${foundryvtt.license_key}
  password: ${foundryvtt.password}
  username: ${foundryvtt.username}
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: foundryvtt
    meta.helm.sh/release-namespace: foundry-vtt
  creationTimestamp: "2025-05-27T20:47:11Z"
  labels:
    app: foundryvtt-foundry-vtt
    app.kubernetes.io/managed-by: Helm
    chart: foundry-vtt-0.1.4
    heritage: Helm
    release: foundryvtt
  name: foundryvtt-foundry-vtt
  namespace: foundry-vtt
  resourceVersion: "7690534"
  uid: 578ba354-7d3c-4857-8dc1-d119aaebbefe
type: Opaque