- Gaming:
        - FoundryVTT:
            href: https://golarion.thoughtcrimegames.net
            description: Pathfinder and other games 
            namespace: foundry-vtt
            app: foundry-vtt