apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foundryvtt-storage
  namespace: foundry-vtt
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
